// ============================================================
//  appstart.js — Phase-1 launch orchestrator
//  Depends on: config.js, license.js  (loaded before this)
//  Do NOT edit this file between projects — edit config.js only.
//
//  Sheet format: SMART DETECTION — column order doesn't matter!
//  The parser reads the header row and matches columns by
//  keyword patterns. Supported fields:
//    - college name, management name, license key, server url,
//      management logo, college logo, maker animation,
//      college animation, college contact no, output sheet id.
//  Columns can be freely reordered, added, or removed.
//
//  Version check: Auto-detected from ./version.json (no sheet).
// ============================================================

const AppStart = (() => {

  // ── Internal state ───────────────────────────────────────
  let _overlay, _animLayer;
  let _licenseKey    = "";   // raw key string
  let _licenseResult = null;
  let _sheetConfig   = {};
  let _serverUrl     = "";
  let _dataPromises  = {};

  // ── Phase index → UI element id ──────────────────────────
  const PHASES = [
    { id: "ph-env",     label: "Device Environment"   },
    { id: "ph-license", label: "License Verification" },
    { id: "ph-server",  label: "Fetching Server URL"  },
    { id: "ph-version", label: "App Version"          },
    { id: "ph-anim",    label: "Branding Assets"      },
    { id: "ph-data",    label: "Data Sync"            },
  ];

  // ── Helpers ───────────────────────────────────────────────
  function _primeAudio() {
    const audio = new Audio();
    audio.src = "data:audio/wav;base64,UklGRigAAABXQVZFRm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQQAAAAAAA== ";
    audio.play().catch(() => {});
  }

  function _applyTheme() {
    const t = APP_CONFIG.THEME;
    const vars = {
      "--as-primary":   t.primary,
      "--as-secondary": t.secondary,
      "--as-danger":    t.danger,
      "--as-bg":        t.bg,
      "--as-surface":   t.surface,
      "--as-border":    t.border,
      "--as-text":      t.text,
      "--as-muted":     t.muted,
    };
    for (const [k, v] of Object.entries(vars)) {
      document.documentElement.style.setProperty(k, v);
    }
  }

  const _enforceTheme = () => {
    document.documentElement.setAttribute("data-theme", "dark");
    document.body.style.background = APP_CONFIG.THEME.bg;
  };

  function _el(id) { return document.getElementById(id); }

  // ── Phase status setters ──────────────────────────────────
  function _setPhase(phId, state, statusText = "") {
    const el = _el(phId);
    if (!el) return;
    el.className = "as-phase " + state;
    const icon   = el.querySelector(".as-phase-icon");
    const status = el.querySelector(".as-phase-status");
    if (icon) {
      if      (state === "done")  icon.textContent = "✓";
      else if (state === "error") icon.textContent = "✕";
      else                        icon.textContent = "";
    }
    if (status) status.textContent = statusText;
  }

  // ── Build the overlay DOM ─────────────────────────────────
  function _buildOverlay() {
    if (document.getElementById("appstart-overlay")) return;
    _applyTheme();
    _enforceTheme();

    _animLayer = document.createElement("div");
    _animLayer.id = "appstart-anim-layer";
    
    // Create double-buffer containers
    const maker = document.createElement("div");
    maker.id = "as-anim-maker";
    maker.className = "as-anim-container";
    
    const college = document.createElement("div");
    college.id = "as-anim-college";
    college.className = "as-anim-container";
    college.style.display = "none";
    
    _animLayer.appendChild(maker);
    _animLayer.appendChild(college);
    document.body.appendChild(_animLayer);

    // ── Apply Theme Variables Immediately ───────────────────
    _overlay = document.createElement("div");
    _overlay.id = "appstart-overlay";

    const phasesHTML = PHASES.map((p, i) => `
      <div class="as-phase" id="${p.id}">
        <div class="as-phase-icon">${i + 1}</div>
        <div class="as-phase-label">${p.label}</div>
        <div class="as-phase-status"></div>
      </div>`).join("");

    _overlay.innerHTML = `
      <div class="as-card" id="as-main-card">
        <div class="as-logo-area">
          <div class="as-app-name">${APP_CONFIG.APP_NAME}</div>
          <div class="as-tagline">Initializing</div>
        </div>
        <div id="as-college-badge-area"></div>
        <div class="as-phases" id="as-phases">${phasesHTML}</div>
        <div class="as-footer">
          v${APP_CONFIG.APP_VERSION}<br>
          App powered by VibeMantra Studio
        </div>
      </div>`;

    document.body.appendChild(_overlay);
  }

  // ── License panel ─────────────────────────────────────────
  function _showLicenseInput(prefillKey = "", errorMsg = "") {
    const card = _el("as-main-card");
    card.innerHTML = `
      <div class="as-logo-area">
        <div class="as-app-name">${APP_CONFIG.APP_NAME}</div>
        <div class="as-tagline">Enter License Key</div>
      </div>
      <div class="as-license-panel">
        <div>
          <div class="as-input-label">10-Digit License Key</div>
          <input class="as-input" id="as-key-input"
            maxlength="10" autocomplete="off" spellcheck="false"
            placeholder="XXXXXXXXXX">
        </div>
        <div class="as-error-msg" id="as-err-msg"></div>
        <button class="as-btn" id="as-key-btn">Activate</button>
        <div style="margin-top: 16px; text-align: center;">
          <button onclick="window.requestLicenseKey()" 
             style="cursor:pointer; color: var(--as-primary); font-size: 0.85rem; font-weight: 600; display: inline-flex; align-items: center; justify-content: center; gap: 6px; padding: 10px 16px; border: 1px solid var(--as-border); border-radius: 8px; background: rgba(59, 130, 246, 0.05); width: 100%; box-sizing: border-box; transition: background 0.2s;"
             onmouseover="this.style.background='rgba(59, 130, 246, 0.12)'"
             onmouseout="this.style.background='rgba(59, 130, 246, 0.05)'">
             🔑 Get Free License Key
          </button>
        </div>
      </div>
      <div class="as-footer">v${APP_CONFIG.APP_VERSION}</div>`;

    const input = _el("as-key-input");
    input.value = prefillKey;
    _el("as-err-msg").textContent = errorMsg;

    _el("as-key-btn").addEventListener("click", async () => {
      _el("as-key-btn").disabled = true;
      // 🔊 PRIME AUDIO & 📺 FULLSCREEN
      _primeAudio();
      try { document.documentElement.requestFullscreen(); } catch(e){}

      const key = _el("as-key-input").value.trim();

      _el("as-err-msg").textContent = "";
      _el("as-key-input").classList.remove("as-error");

      const result = License.validate(key);
      if (!result.ok) {
        const msg = result.reason === "expired"
          ? `⛔ License expired on ${result.expiryDate.toLocaleDateString()} (${result.collegeName})`
          : "⛔ Invalid license key. Please check and try again.";
        _el("as-key-input").classList.add("as-error");
        _el("as-err-msg").textContent = msg;
        if (result.reason === "expired") {
          setTimeout(() => _showLockScreen(result), 1200);
        }
        _el("as-key-btn").disabled = false;
        return;
      }

      await KeyStore.save(key);
      _licenseKey    = key;
      _licenseResult = result;
      _showProgressCard(result);
      _runPhases();
    });

    _el("as-key-input").addEventListener("keydown", e => {
      if (e.key === "Enter") _el("as-key-btn").click();
    });
    setTimeout(() => _el("as-key-input")?.focus(), 100);
  }

  // ── Lock screen ───────────────────────────────────────────
  function _showLockScreen(licResult) {
    const card = _el("as-main-card");
    const isExpired = licResult?.reason === "expired";
    card.innerHTML = `
      <div class="as-lock-screen">
        <div class="as-lock-icon">🔒</div>
        <div class="as-lock-title">${isExpired ? "License Expired" : "Access Denied"}</div>
        <div class="as-lock-college" id="as-lock-college"></div>
        <div class="as-lock-sub" id="as-lock-sub"></div>
        <button class="as-btn as-retry-btn" style="background:var(--as-danger);max-width:200px">
          Try Another Key
        </button>
      </div>`;

    if (licResult?.collegeName) _el("as-lock-college").textContent = licResult.collegeName;
    _el("as-lock-sub").innerHTML = isExpired 
      ? `Your license expired on <strong>${licResult.expiryDate.toLocaleDateString()}</strong>.<br>Please <button onclick="window.requestLicenseKey('${licResult.collegeName.replace(/'/g, "\\'")}')" style="cursor:pointer;color:var(--as-primary);background:none;border:none;font-size:inherit;font-weight:600;padding:0;text-decoration:underline;">contact the developer</button> to renew.`
      : `The entered key is invalid.<br>Please <button onclick="window.requestLicenseKey()" style="cursor:pointer;color:var(--as-primary);background:none;border:none;font-size:inherit;font-weight:600;padding:0;text-decoration:underline;">contact the developer</button> for a free key.`;

    card.querySelector(".as-retry-btn").addEventListener("click", () => _clearAndRetry());
  }

  // ── Error screen ──────────────────────────────────────────
  function _showErrorScreen(msg) {
    const card = _el("as-main-card");
    card.innerHTML = `
      <div class="as-lock-screen">
        <div class="as-lock-icon">⚠️</div>
        <div class="as-lock-title">Connection Failed</div>
        <div class="as-lock-sub">${msg}</div>
        <button class="as-btn as-retry-btn" style="background:var(--as-danger);max-width:200px">
          Try Again
        </button>
      </div>`;
    card.querySelector(".as-retry-btn").addEventListener("click", () => location.reload());
  }

  // ── Progress card (phases view) ───────────────────────────
  function _showProgressCard(licResult) {
    const phasesHTML = PHASES.map((p, i) => `
      <div class="as-phase" id="${p.id}">
        <div class="as-phase-icon">${i + 1}</div>
        <div class="as-phase-label">${p.label}</div>
        <div class="as-phase-status"></div>
      </div>`).join("");

    const daysLeft = License.daysRemaining(licResult.expiryDate);
    const expStr   = licResult.expiryDate.toLocaleDateString();
    const badgeNote = daysLeft <= 30
      ? ` · ⚠ ${daysLeft}d left`
      : ` · ${expStr}`;

    _el("as-main-card").innerHTML = `
      <div class="as-logo-area">
        <div class="as-app-name">${APP_CONFIG.APP_NAME}</div>
        <div class="as-tagline">Starting up…</div>
      </div>
      <div class="as-college-badge" id="as-college-badge">
        <div class="as-college-dot"></div>
        <span id="as-college-name"></span>
      </div>
      <div class="as-phases" id="as-phases">${phasesHTML}</div>
      <div class="as-footer">v${APP_CONFIG.APP_VERSION}</div>`;
      
    _el("as-college-name").textContent = `${licResult.collegeName}${badgeNote}`;
  }

  // ── Smart column-name keyword map ─────────────────────────
  // Each field has an array of keyword patterns to match against
  // the header text (lowercased, trimmed). Order doesn't matter.
  const COLUMN_KEYWORDS = {
    college_name:      ["college name", "college", "institution", "inst name"],
    management_name:   ["management name", "management", "trust", "society", "mgmt name"],
    license_key:       ["license key", "license", "key", "activation", "licence"],
    server_url:        ["server url", "server", "api url", "backend", "api"],
    sheet_id:          ["sheet id", "sheetid", "spreadsheet id", "sheet_id", "input sheet id", "input_sheet_id"],
    management_logo:   ["management logo", "mgmt logo", "trust logo"],
    college_logo:      ["college logo", "institution logo", "inst logo"],
    output_sheet_id:   ["output sheet id", "output id", "output excel link", "output link"],
    maker_animation:   ["maker animation", "maker anim", "maker"],
    college_animation: ["college animation", "college anim"],
    contact_no:        ["college contact", "contact no", "contact", "phone", "mobile"],
  };

  // ── Detect header row and build column map ────────────────
  // Returns { field_name: column_index } by matching header text
  // against COLUMN_KEYWORDS. Longer keyword matches win to avoid
  // false positives (e.g. "college name" beats "college").
  function _buildColumnMap(rows, isCsv, gvizCols = null) {
    let headers = [];
    let headerIdx = -1;

    // Strategy A: If it's GViz and we have col metadata, use that first
    if (gvizCols && gvizCols.length >= 3) {
      headers = gvizCols.map(c => String(c.label || "").trim().toLowerCase());
      headerIdx = -1; // Data starts at row 0 of json.table.rows
    }

    // Strategy B: Scan rows for headers (fallback or CSV)
    const validHeaders = headers.filter(h => String(h).trim().length > 0);
    // Only trust Strategy A if headers are non-empty AND we find at least one match
    const hasMappedHeaders = (window.Translator && typeof window.Translator.findHeader === 'function') 
      ? headers.some(h => window.Translator.findHeader([h], Object.values(COLUMN_KEYWORDS).flat())) 
      : false;

    if (validHeaders.length < 3 || !hasMappedHeaders) {
      console.log("⚠️ AppStart: Strategy A weak or no labels. Switching to Strategy B (Scan Rows)...");
      let headerRow = null;
      for (let i = 0; i < Math.min(rows.length, 5); i++) {
        const cells = isCsv ? rows[i] : (rows[i].c || []);
        const textCount = cells.filter(c => {
          const val = isCsv ? c : c?.v;
          return val && isNaN(Number(val));
        }).length;
        if (textCount >= 3) {
          headerRow = cells;
          headerIdx = i;
          break;
        }
      }
      if (!headerRow) throw new Error("Could not detect header row in config sheet.");

      headers = headerRow.map(c => {
        const val = isCsv ? c : c?.v;
        return val ? String(val).trim().toLowerCase() : "";
      });
    }


    // Match each field to a column index
    const colMap = {};
    for (const [field, keywords] of Object.entries(COLUMN_KEYWORDS)) {
      // Sort keywords longest-first so specific matches win
      const sorted = [...keywords].sort((a, b) => b.length - a.length);
      for (const kw of sorted) {
        const idx = headers.findIndex(h => h.includes(kw));
        if (idx !== -1) {
          colMap[field] = idx;
          break;
        }
      }
    }

    console.log("AppStart: detected column map →", colMap);
    return { colMap, headerIdx };
  }

  // ── Google Sheet parser (smart header detection) ──────────
  // Scans headers to detect columns, then finds the row where
  // the license_key column matches the provided key.
  // Robust request helper (replaces fetch for better CORS/Network error visibility)
  function _rawRequest(url) {
    return new Promise((resolve, reject) => {
      if (window.location.protocol === "file:") {
        return reject(new Error("Browsers block Google Sheets on 'file://'. Please use a local server."));
      }
      const xhr = new XMLHttpRequest();
      const sep = url.includes("?") ? "&" : "?";
      xhr.open("GET", url + `${sep}t=${Date.now()}`);
      xhr.timeout = 8000;
      xhr.onload = () => {
        if (xhr.status >= 200 && xhr.status < 300) resolve(xhr.responseText);
        else reject(new Error(`Server error ${xhr.status}: ${xhr.statusText || "Forbidden"}`));
      };
      xhr.onerror = () => reject(new Error("Network Error (Blocked by Browser/CORS)"));
      xhr.ontimeout = () => reject(new Error("Request Timed Out"));
      xhr.send();
    });
  }

  async function _request(url, retries = 2, delay = 500) {
    for (let i = 0; i <= retries; i++) {
      try {
        const text = await _rawRequest(url);
        const trimmed = text.trim();
        if (trimmed.startsWith("<!DOCTYPE") || trimmed.startsWith("<html") || trimmed.startsWith("<script")) {
          throw new Error("Google Sheets returned HTML instead of data (verify sheet sharing).");
        }
        return text;
      } catch (err) {
        if (i === retries) throw err;
        console.warn(`AppStart: Request failed (attempt ${i + 1}/${retries + 1}). Retrying in ${delay}ms...`, err);
        await new Promise(r => setTimeout(r, delay));
        delay *= 2;
      }
    }
  }

  async function _fetchSheetConfig(url, licenseKey) {
    let rows = [];
    let isCsv = false;
    let colMap = null;
    let headerIdx = -1;

    try {
      const text = await _request(url);
      const json = JSON.parse(text.replace(/^.*?setResponse\(/s, "").replace(/\);\s*$/s, ""));
      rows = json.table?.rows || [];
      const { colMap: detectedMap, headerIdx: detectedIdx } = _buildColumnMap(rows, false, json.table?.cols);
      colMap = detectedMap;
      headerIdx = detectedIdx;
    } catch (err) {
      console.warn("AppStart: JSON request failed, trying CSV fallback...", err);
      try {
        const csvUrl = url.replace(/\/(edit|gviz\/tq).*$/i, "/export?format=csv");
        const csvText = await _request(csvUrl);
        rows = _parseCSV(csvText);
        isCsv = true;
      } catch (err2) {
        throw new Error(err.message.includes("file:") ? err.message : `Connection Failed: ${err2.message || err.message}`);
      }
    }


    if (!colMap) {
      const { colMap: detectedMap, headerIdx: detectedIdx } = _buildColumnMap(rows, isCsv);
      colMap = detectedMap;
      headerIdx = detectedIdx;
    }

    // Ensure we found a license key column
    if (colMap.license_key === undefined) {
      throw new Error("Could not find 'license key' column in config sheet.");
    }

    // Helper to extract a cell value by field name
    const _v = (row, field) => {
      const idx = colMap[field];
      if (idx === undefined) return "";
      // JSON format has { c: [ { v: 'val' } ] }, CSV parser already returns simple strings
      const cell = isCsv ? row[idx] : row.c?.[idx]?.v;
      return cell ? String(cell).trim() : "";
    };

    // Search data rows (skip header and any rows above it)
    // For GViz with labels, headerIdx is -1, so we start at row 0.
    // For CSV/Fallback, headerIdx is the row index of labels, so we start at headerIdx + 1.
    for (let i = headerIdx + 1; i < rows.length; i++) {
      const row = rows[i];
      const sheetKey = _v(row, "license_key");
      if (sheetKey && sheetKey === String(licenseKey).trim()) {
        return {
          college_name:      _v(row, "college_name"),
          management_name:   _v(row, "management_name"),
          license_key:       _v(row, "license_key"),
          server_url:        _v(row, "server_url"),
          sheet_id:          _v(row, "sheet_id"),
          management_logo:   _v(row, "management_logo"),
          college_logo:      _v(row, "college_logo"),
          maker_animation:   _v(row, "maker_animation"),
          college_animation: _v(row, "college_animation"),
          contact_no:        _v(row, "contact_no"),
          output_sheet_id:   _v(row, "output_sheet_id"),
        };
      }
    }

    throw new Error("License key not found in config sheet. Please contact your administrator.");
  }

  // Basic CSV parser (handles quoted values with commas)
  function _parseCSV(text) {
    const rows = [];
    const lines = text.split(/\r?\n/);
    for (const line of lines) {
      if (!line.trim()) continue;
      const cells = [];
      let current = "";
      let inQuotes = false;
      for (let i = 0; i < line.length; i++) {
        const char = line[i];
        if (char === '"' && line[i+1] === '"') { current += '"'; i++; }
        else if (char === '"') { inQuotes = !inQuotes; }
        else if (char === ',' && !inQuotes) { cells.push(current); current = ""; }
        else { current += char; }
      }
      cells.push(current);
      rows.push(cells);
    }
    return rows;
  }


  // ── Utilities ─────────────────────────────────────────────
  function _sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

  // ── Auto version check via version.json (SINGLE SOURCE OF TRUTH) ──
  async function _checkVersionUpdate() {
    try {
      const res = await Promise.race([
        fetch(`./version.json?t=${Date.now()}`),
        new Promise((_, reject) => setTimeout(() => reject(new Error("Timeout")), 8000))
      ]);
      if (!res.ok) return null;
      const data = await res.json();
      const serverVersion = data.version;
      if (!serverVersion) return null;

      // Read BEFORE overwriting
      const cachedVersion = await KeyStore.getItem("appstart_cached_version") || "unknown";

      // Now set display version
      APP_CONFIG.APP_VERSION = serverVersion;

      if (!cachedVersion || cachedVersion === "unknown") {
        KeyStore.setItem("appstart_cached_version", serverVersion);
        return null;
      }

      if (cachedVersion !== serverVersion) {
        // Server has a different version than what we last booted with
        KeyStore.setItem("appstart_cached_version", serverVersion);
        if (data.forceUpdate) return { from: cachedVersion, to: serverVersion };
      }

      return null;
    } catch {
      return null;
    }
  }

  // ── Force update screen ──────────────────────────────────
  function _showUpdateScreen(versionData) {
    const card = _el("as-main-card");
    const from = versionData.from || "old";
    const to   = versionData.to || "new";

    card.innerHTML = `
      <div class="as-update-screen">
        <div class="as-update-icon">🚀</div>
        <div class="as-update-title">Update Available</div>
        <div class="as-version-badge">
          <span>v${from}</span>
          →
          <span class="new">v${to}</span>
        </div>
        <p style="font-size:0.8rem;color:var(--as-muted);line-height:1.6;text-align:center;margin-top:4px">
          A newer version of this app is available.<br>
          Please update to continue.
        </p>
        <button class="as-btn" onclick="location.reload()" style="max-width:240px">Refresh Now</button>
      </div>`;
  }


  // ── Animation player ──────────────────────────────────────
  async function _playAnimation(url, labelText) {
    if (!url) return;
    return new Promise(resolve => {
      _animLayer.innerHTML = "";
      _animLayer.classList.add("as-visible");

      const label = document.createElement("div");
      label.className = "as-anim-label";
      label.textContent = labelText;
      _animLayer.appendChild(label);

      const ext = url.split(".").pop().toLowerCase().split("?")[0];

      if (ext === "json") {
        _loadLottie(() => {
          if (!window.lottie) { _hideAnimLayer(resolve); return; }
          const container = document.createElement("div");
          container.style.cssText = "width:100%;height:100%;display:flex;align-items:center;justify-content:center;";
          _animLayer.appendChild(container);
          const anim = lottie.loadAnimation({
            container, renderer: "svg", loop: false, autoplay: true, path: url,
          });
          let resolved = false;
          const onComplete = () => {
            if (resolved) return;
            resolved = true;
            _hideAnimLayer(resolve);
          };
          anim.addEventListener("complete", onComplete);
          // Fallback for long Lottie
          setTimeout(onComplete, 8000);
        });
      } else if (["mp4", "webm", "ogg"].includes(ext)) {
        const video = document.createElement("video");
        video.src = url; 
        video.autoplay = true; 
        video.muted = false; // SOUND ON
        video.playsInline = true;
        video.style.cssText = "width:100vw;height:100vh;object-fit:cover;object-position:center;";
        
        video.onended = () => _hideAnimLayer(resolve);
        video.onerror = () => _hideAnimLayer(resolve);
        
        _animLayer.appendChild(video);
        
        video.play().catch(err => {
          console.warn("Autoplay with sound blocked, trying muted...", err);
          video.muted = true;
          video.play();
        });
      } else {
        // GIF / image — display for 4s
        const img = document.createElement("img");
        img.src = url;
        img.style.cssText = "max-width:90%;max-height:80vh;object-fit:contain;";
        _animLayer.appendChild(img);
        setTimeout(() => _hideAnimLayer(resolve), 4000);
      }
    });
  }


  function _hideAnimLayer(resolve) {
    // Keep opaque to hide the underlying tick status window
    setTimeout(resolve, 500);
  }

  function _loadLottie(cb) {
    if (window.lottie) { cb(); return; }
    const s = document.createElement("script");
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/bodymovin/5.12.2/lottie.min.js";
    s.onload = cb;
    s.onerror = () => { console.warn("Lottie CDN failed"); cb(); };
    document.head.appendChild(s);
  }

  // ── Main phase runner ─────────────────────────────────────
  async function _runPhases() {
    // Phase 0: Environment Detection
    _setPhase("ph-env", "active", "Scanning…");
    await _sleep(300);
    const w = window.innerWidth, h = window.innerHeight;
    const isMobile = /Mobi|Android|iPhone/i.test(navigator.userAgent);
    const orientation = w > h ? "Landscape" : "Portrait";
    const type = isMobile ? (w < 600 ? "Mobile" : "Tablet") : "Desktop";
    _setPhase("ph-env", "done", `${type} ${orientation} (${w}x${h})`);

    // Phase 1: License (already validated)
    _setPhase("ph-license", "active", "Checking…");
    await _sleep(200);
    _setPhase("ph-license", "done", _licenseResult.collegeName);

    // Phase 2: Fetch GSheet Config (CRITICAL: Must happen before animations)
    _setPhase("ph-server", "active", "Connecting…");
    try {
      _sheetConfig = await _fetchSheetConfig(APP_CONFIG.CONFIG_SHEET_URL, _licenseKey);
      const sheetId = _sheetConfig["sheet_id"] || "";
      _serverUrl = _sheetConfig["server_url"] || "";
      
      if (!sheetId && !_serverUrl) {
        throw new Error("Server URL or Sheet ID empty");
      }
      
      // If we have a sheetId and a Central API URL is configured, use the Central API
      if (sheetId && APP_CONFIG.CENTRAL_API_URL) {
        _serverUrl = APP_CONFIG.CENTRAL_API_URL;
      }
      
      const displayUrl = _serverUrl || `Sheet ID: ${sheetId}`;
      _setPhase("ph-server", "done", displayUrl.substring(0, 24) + "...");
    } catch (err) {
      _setPhase("ph-server", "error", err.message || "Failed");
      console.error("AppStart: config fetch failed →", err);
      setTimeout(() => _showErrorScreen(err.message || "Failed to load config."), 1000);
      return; // Cannot continue without config
    }

    // Phase 3: Version check
    _setPhase("ph-version", "active", "Checking…");
    const newVer = await _checkVersionUpdate();
    if (newVer) {
      _setPhase("ph-version", "error", `v${newVer.to} available`);
      _showUpdateScreen(newVer);
      return;
    }
    _setPhase("ph-version", "done", `v${APP_CONFIG.APP_VERSION} ✓`);

    // 🔥 TRACK B (Visual Overlay): Start Branding Sequence
    _setPhase("ph-anim", "active", "Branding…");
    
    // 🚀 TRACK A (Background): Start Background Data Fetch
    _setPhase("ph-data", "active", "Background…");
    const dataPromise = (async () => {
      try {
        await _startDataFetch();
        const keys = Object.keys(_dataPromises);
        if (keys.length === 0) return {};
        const results = await Promise.allSettled(keys.map(k => _dataPromises[k]));
        const fetched = {};
        let failedCount = 0;
        keys.forEach((k, i) => {
          if (results[i].status === "fulfilled") fetched[k] = results[i].value;
          else { fetched[k] = null; failedCount++; }
        });
        if (failedCount > 0) throw new Error(`${failedCount} source(s) failed`);
        return fetched;
      } catch (e) {
        throw e;
      }
    })();

    // Transition to Fullscreen Animations
    try {
      const makerUrl   = _sheetConfig["maker_animation"] || "";
      const collegeUrl = _sheetConfig["college_animation"] || "";
      
      if (makerUrl)   await _playAnimation(makerUrl, "Powered by");
      if (collegeUrl) await _playAnimation(collegeUrl, _licenseResult.collegeName);
      
      _setPhase("ph-anim", "done", "Complete");
    } catch (err) {
      _setPhase("ph-anim", "error", "Skipped");
      console.warn("AppStart: animation failed →", err);
    }

    // 🏁 Sync Tracks
    try {
      const fetchedData = await dataPromise;
      _setPhase("ph-data", "done", `${Object.keys(fetchedData).length} source(s) ready`);
      
      const resultPayload = {
        collegeName:    _licenseResult.collegeName,
        managementName: _sheetConfig["management_name"]  || "",
        expiryDate:     _licenseResult.expiryDate,
        serverUrl:      _serverUrl,
        sheetId:        _sheetConfig["sheet_id"] || "",
        managementLogo: _sheetConfig["management_logo"]  || "",
        collegeLogo:    _sheetConfig["college_logo"]     || "",
        contactNo:      _sheetConfig["contact_no"]       || "",
        config:         _sheetConfig,
        fetchedData,
      };

      window.appStartContext = resultPayload;
      document.dispatchEvent(new CustomEvent("appstart:complete", { detail: resultPayload }));
      if (typeof APP_CONFIG.onComplete === "function") APP_CONFIG.onComplete(resultPayload);

      // Final Cleanup
      await _sleep(500); // Wait a moment so user can see completion
      _overlay.remove();
      _animLayer.remove();
    } catch (err) {
      // DATA FETCH FAILED — Reshow status screen with error
      if (_animLayer) _animLayer.classList.remove("as-visible");
      console.error("AppStart: background data fetch failed →", err);
      _setPhase("ph-data", "error", err.message || "Fetch failed");
      setTimeout(() => _showErrorScreen(err.message || "Failed to fetch data."), 1000);
    }
  }


  // ── Background data fetch ─────────────────────────────────
  const _startDataFetch = async () => {
    if (!APP_CONFIG.dataFetcher) return;

    // 1. Execute the fetcher (might be async or return a map of promises)
    const promisesOrMap = await APP_CONFIG.dataFetcher(_serverUrl, _sheetConfig["sheet_id"] || "");

    if (!promisesOrMap) return;

    // 2. If it's a direct promise, wrap it
    if (typeof promisesOrMap.then === "function") {
      _dataPromises = { _default: promisesOrMap };
    } else {
      _dataPromises = promisesOrMap;
    }
    
    console.log("📡 AppStart: Data fetch sequence started.", Object.keys(_dataPromises));
  };

  // ── Public: clear stored key and retry ────────────────────
  async function _clearAndRetry() {
    await KeyStore.clear();
    _licenseKey = "";
    _showLicenseInput();
  }

  // ── init() ────────────────────────────────────────────────
  async function init() {
    _buildOverlay();

    const stored = await KeyStore.load();

    if (stored) {
      const result = License.validate(stored);
      if (result.ok) {
        await KeyStore.save(stored);
        _licenseKey    = stored;
        _licenseResult = result;
        _showProgressCard(result);
        _runPhases();
        return;
      }
      await KeyStore.clear();
      if (result.reason === "expired") {
        _showLicenseInput(
          stored,
          `⛔ License expired on ${result.expiryDate.toLocaleDateString()} (${result.collegeName})`
        );
      } else {
        _showLicenseInput(stored, "⛔ Stored key is invalid. Re-enter your key.");
      }
    } else {
      _showLicenseInput();
    }
  }

  return { init, _clearAndRetry };
})();

// Global secure license key request handler
// Always opens Gmail Web (works on ALL devices - mobile & desktop)
// Avoids blank page / Outlook issues caused by mailto: on devices without email clients
window.requestLicenseKey = function(collegeName = "") {
  const email = "pranavparekhcontent@gmail.com";
  const subject = collegeName ? "Smart Attendance - Renew License" : "Smart Attendance - Request Free License Key";
  const body = collegeName 
    ? `Hi Pranav,\n\nI would like to renew the expired license key for the Smart Attendance app.\n\nMy details:\nName: \nMobile No: \nCollege: ${collegeName}`
    : `Hi Pranav,\n\nI would like to request a free license key for the Smart Attendance app.\n\nMy details:\nName: \nMobile No: \nInstitution/College: `;
  
  // Always use Gmail Web — works on Android Chrome, iOS Safari, and Desktop.
  // mailto: is unreliable (opens Outlook on Windows, blank on Android without email app).
  const gmailUrl = `https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(email)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  window.open(gmailUrl, '_blank', 'noopener,noreferrer');
};
